### ISSUE TITLE
Re-enable IntroActivity tests

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1754]
**Type of Test**

* [ ] Unit Test
* [x] UI Test

**Current Status of the tests**
On CI this test would sometimes fail.
This was generally not being able to swipe the view and see the views on the other page.

Operating theory is that a system dialog was interfering at times, preventing view interaction

**Comment by yashk2000** [comment]
@macgills I wasn't able to figure out this issue. 
I tried to run the test on my device after removing `@Ignore`.
The test ran successfully on my device.

**Comment by macgills** [comment]
@yashk2000 they always ran for me successfully, the problem is on the CI. You would have to open a PR, configure the workflow so it runs on all available emulators (like it does on the nightly build) and run that a bunch of times until you are confident that the test is not flaky

**Comment by yashk2000** [comment]
@macgills so like in the nightly build, I have to add the following section to the pull request build?

```
instrumentation_tests:
    strategy:
      matrix:
        api-level: [21, 22, 23, 24, 25, 27, 28, 29]
      fail-fast: false
    runs-on: macOS-latest
    steps:

      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2.0.0
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          script: ./gradlew connectedDebugAndroidTest
```
