### ISSUE TITLE
Publish 3.3 on FDroid

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1840]

**Comment by yashk2000** [comment]
@kelson42 I'd like to take this up. 
I have an idea on how to add a new app to fdroid. 
Could you please tell me how do we update an existing app on fdroid?

**Comment by kelson42** [comment]
@yashk2000 Thx, look at #1698

**Comment by yashk2000** [comment]
@kelson42 I just wanted to confirm the version code. `230201` is the current version code right?
I am referring to https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6232/diffs for sending the merge request.

**Comment by kelson42** [comment]
@yashk2000 I can not help you for that, you need to ask other devs. But obviously, this is not the same naymore.

**Comment by kelson42** [comment]
@yashk2000 I guess the new code should be `30201` yes

**Comment by yashk2000** [comment]
@kelson42 I made the merge request on GitLab. 

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6415

**Comment by yashk2000** [comment]
@kelson42 could you please take a look at the discussion on the thread?
Currently the latest release of the app is 3.1.3. 
I think we'll need to shift 3.2.1 from pre-release to the latest release.

**Comment by yashk2000** [comment]
@macgills could I please get some help here?
The apk which is generated seems to be signed already. The `disableSigning` config seems to not be working as expected.

**Comment by kelson42** [comment]
@yashk2000 You are not able to fix the option yourself? Or understand what goes wrong?

**Comment by yashk2000** [comment]
@kelson42 this is the code that handles the `release` configuration: 

```
getByName("release") {
      buildConfigField("boolean", "KIWIX_ERROR_ACTIVITY", "true")
      if (properties.containsKey("disableSigning")) {
        signingConfig = null
      }
    }
```

Here the signing config is made null.
This should work if a release apk is being made. So I generated release apks for the application and ran the following command:

`apksigner verify --print-certs dev-universal-release.apk`

Here, it shows that the apk is already signed. 

`Signer #1 certificate DN: CN=Alexandre Saveau, OU=Robot Scouter, O=SUPERCILEX`

If the apk was unsinged, this shouldn't have been the value of CN. 

I'm not sure how to give disableSigning as an option in the input to test what's happening or whether disableSigning is automatically taken as an input.

**Comment by yashk2000** [comment]
I removed this condition: 

```
if (properties.containsKey("disableSigning")) {
        signingConfig = null
      }
```

I just put `signingConfig = null` without a condition which worked. So I want to know how to give disableSigning as an input paramter while generating apks inorder to test it. Or whether it is automatically there.

**Comment by macgills** [comment]
that property is there so when it is built on fdroid's side it does not try to sign it for example
```
gradlew -PdisableSigning app:assembleRelease
```
will produce an unsigned apk.

Kiwix has dummy credentials in source control so people can sign things locally without issue and our build are more repeatable. On CI these dummy credentials get overwritten and the real signing keys are used.

The only thing I see different in the merge request is there is no `.gradle` under `scanIgnore`

```
  - versionName: 3.1.3
    versionCode: 230103
    commit: 3.1.4
    subdir: app
    gradle:
      - yes
    output: build/outputs/apk/release/dev-universal-release-unsigned.apk
    scanignore:
      - buildSrc
      - .gradle
    gradleprops:
      - disableSigning

  - versionName: 3.2.1
    versionCode: 230201
    commit: 3.2.1
    subdir: app
    gradle:
      - yes
    output: build/outputs/apk/release/dev-universal-release.apk
    scanignore:
      - buildSrc
    gradleprops:
      - disableSigning
```

If disableSigning has been broken you should investigate why. For the fdroid build we want signingconfig to be null
